package:
  name: ssl
  version: 1.0.0 # Nonsense
  top-level:
    - ssl
    - _ssl
  tag:
    - core
source:
  sha256: $(PYTHON_ARCHIVE_SHA256)
  url: $(PYTHON_ARCHIVE_URL)
build:
  type: cpython_module
  script: |
    emcc $STDLIB_MODULE_CFLAGS -c Modules/_ssl.c -o Modules/_ssl.o \
      $(pkg-config --cflags --dont-define-prefix openssl) \
      $(pkg-config --libs --dont-define-prefix openssl) \
      -DOPENSSL_THREADS # This declares that OPENSSL is threadsafe. We are single threaded so everything is threadsafe.
    emcc Modules/_ssl.o -o $DISTDIR/_ssl.so $SIDE_MODULE_LDFLAGS $(pkg-config --libs --dont-define-prefix openssl)

    cp Lib/ssl.py $DISTDIR
requirements:
  host:
    - openssl
  run:
    - openssl
